version: '3'
services:
  asset_logging_db:
    image: mysql:8.0
    working_dir: /server
    volumes:
      - db_data:/var/lib/mysql  # Named volume for services persistence
      - .:/server
    ports:
      - 3701:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: asset-logging
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq-asset-logging'
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
volumes:
  db_data:
networks:
  rabbitmq_nodejs:
    driver: bridge